# Generated by Django 5.0.7 on 2024-08-03 06:56

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('profile', models.CharField(max_length=256, verbose_name='profile')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('description', models.TextField(verbose_name='description')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[200, 200], upload_to='Profile/')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog categories',
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'blog tag',
                'verbose_name_plural': 'blog tags',
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[200, 200], upload_to='Profile/')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('is_top', models.BooleanField(default=False, verbose_name='blog is top')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(max_length=256, verbose_name='author')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[540, 304], upload_to='blog/', verbose_name='main image')),
                ('large_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[1100, 700], upload_to='blog/', verbose_name='large image')),
                ('read_time', models.IntegerField(verbose_name='read time')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('categories', models.ManyToManyField(related_name='blogs', to='common.blogcategory', verbose_name='categories')),
                ('tags', models.ManyToManyField(related_name='blogs', to='common.blogtag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('comment', models.TextField(verbose_name='comment')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.blog', verbose_name='blog')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.blogcomment', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'blog comment',
                'verbose_name_plural': 'blog comments',
                'db_table': 'blog_comment',
            },
        ),
        migrations.CreateModel(
            name='Portfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[400, 320], upload_to='Profile/')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('categories', models.ManyToManyField(related_name='portfiles', to='common.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'portfile',
                'verbose_name_plural': 'portfiles',
                'db_table': 'portfile',
            },
        ),
    ]
