# Generated by Django 5.0.7 on 2024-08-06 10:45

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='backgraund',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=2, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[1920, 1080], upload_to='Profile/'),
            preserve_default=False,
        ),
    ]
